import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  CurrencyDollarSimple,
  Plus,
  User,
} from "@phosphor-icons/react/dist/ssr";
import { Profile } from "@/components/profile";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { CreateBudgetDialog } from "@/components/create-budget-dialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
